[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
splurge = "4Vgt9GWkVtW5Pf8MNfGQYEVYRiAyen4QWnCXH5jeXnft"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "splurge-wallet.json"

[scripts]
test = "bun test --timeout 1000000"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
