[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
splurge = "SPLGqkZN8mAFsFjzMe6LZ4yeCzY6i6SGhegF9qQWaL7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "splurge-wallet.json"

[scripts]
test = "bun test --timeout 1000000"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
